[package]
name = "voxel-vulkano"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.35.1"
vulkano-shaders = "0.35"
winit = "0.30.11"
image = "0.25.6"
shaderc = "0.8.3"
nalgebra = "0.34.0"
noise = "0.9"
bytemuck = "1.23.2"
dot_vox = "5.1.1"
glam = "0.30.8"